ERRORS :::::  chage the id to string and class name mismatch rename as ApplicationUser and added using in program.cs they were missing
/Controllers/BookingController.cs(72,26): error CS0029: Cannot implicitly convert type 'string' to 'int'
change to string id

The type or namespace name 'ApplicationUser' could not be found
class name mismatch

Unreachable code detected???

IdentityBuilder' does not contain a definition for 'AddDefaultTokenProviders' this means i did not installed it installed it but all of them are installed

   Backend-Resourcely   git:(JaniduLoginSignupTest)  dotnet list package
Project 'Backend-Resourcely' has the following package references
   [net9.0]:
   Top-level Package                                        Requested   Resolved
   > Microsoft.AspNetCore.Identity.EntityFrameworkCore      9.0.9       9.0.9
   > Microsoft.AspNetCore.Identity.UI                       9.0.9       9.0.9
   > Microsoft.AspNetCore.OpenApi                           9.0.8       9.0.8
   > Microsoft.EntityFrameworkCore                          9.0.9       9.0.9
   > Microsoft.EntityFrameworkCore.Design                   9.0.9       9.0.9
   > Microsoft.EntityFrameworkCore.Tools                    9.0.9       9.0.9
   > Pomelo.EntityFrameworkCore.MySql                       9.0.0       9.0.0
   > Swashbuckle.AspNetCore                                 9.0.4       9.0.4