Edit :: missing conf for supervisord
error
#30 resolve docker.io/library/node:20-alpine@sha256:eabac870db94f7342d6c33560d6613f188bbcf4bbe1f4eb47d5e2a08e1a37722 0.0s done
#30 DONE 0.0s

#31 [runtime  1/11] FROM mcr.microsoft.com/dotnet/aspnet:9.0@sha256:366204b1d249aa2615f4942c8549677a1f3e6231829f274aa8829fc048f38d8c
#31 resolve mcr.microsoft.com/dotnet/aspnet:9.0@sha256:366204b1d249aa2615f4942c8549677a1f3e6231829f274aa8829fc048f38d8c done
#31 DONE 0.1s

#32 [backend-build 1/7] FROM mcr.microsoft.com/dotnet/sdk:9.0@sha256:123b43e4d9775451d8ed63af324a42132707b4edb14770bcdf5c85cf55bc45f1
#32 resolve mcr.microsoft.com/dotnet/sdk:9.0@sha256:123b43e4d9775451d8ed63af324a42132707b4edb14770bcdf5c85cf55bc45f1 done
#32 DONE 0.1s
------
 > [runtime 11/11] COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf:
------
Dockerfile:71
--------------------
  69 |     # MY FIX - Use supervisor as proper process manager
  70 |     RUN apt-get update && apt-get install -y supervisor
  71 | >>> COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf
  72 |
  73 |     CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
--------------------
ERROR: failed to build: failed to solve: failed to compute cache key: failed to calculate checksum of ref ntlcajlx4ej0uo0tacscyxsan::74g5gkq2j25lmhsj6fpdmmoc6: "/supervisord.conf": not found
Error: buildx failed with: ERROR: failed to build: failed to solve: failed to compute cache key: failed to calculate checksum of ref ntlcajlx4ej0uo0tacscyxsan::74g5gkq2j25lmhsj6fpdmmoc6: "/supervisord.conf": not found