ERROR :: docker backend error cant publish and missing npm improts added to vite
 => CACHED [backend build 5/6] COPY . ./                                                                      0.0s
 => ERROR [backend build 6/6] RUN dotnet publish -c Release -o /app/publish                                   2.8s
 => [frontend internal] load .dockerignore                                                                    0.0s
 => => transferring context: 53B                                                                              0.0s
 => [frontend 1/5] FROM docker.io/library/node:22-alpine@sha256:cb3143549582cc5f74f26f0992cdef4a422b22128cb5  0.0s
 => => resolve docker.io/library/node:22-alpine@sha256:cb3143549582cc5f74f26f0992cdef4a422b22128cb517f94173a  0.0s
 => [frontend internal] load build context                                                                    0.0s
 => => transferring context: 338.79kB                                                                         0.0s
 => CACHED [frontend 2/5] WORKDIR /app                                                                        0.0s
 => [frontend 3/5] COPY package*.json ./                                                                      0.0s
 => CANCELED [frontend 4/5] RUN npm ci                                                                        1.5s
------
 > [backend build 6/6] RUN dotnet publish -c Release -o /app/publish:
0.567   Determining projects to restore...
0.843   All projects are up-to-date for restore.
0.854 /usr/share/dotnet/sdk/9.0.305/Current/SolutionFile/ImportAfter/Microsoft.NET.Sdk.Solution.targets(36,5): warning NETSDK1194: The "--output" option isn't supported when building a solution. Specifying a solution-level output path results in all projects copying outputs to the same directory, which can lead to inconsistent builds. [/src/Backend-Resourcely.sln]
2.738 /src/Helpers/DatabaseInitializer.cs(2,7): error CS0246: The type or namespace name 'MySqlConnector' could not be found (are you missing a using directive or an assembly reference?) [/src/Backend-Resourcely.csproj]
------
dockerfile:10

--------------------

   8 |     # Copy everything else and build

   9 |     COPY . ./

  10 | >>> RUN dotnet publish -c Release -o /app/publish

  11 |

  12 |     # Runtime image

--------------------

target backend: failed to solve: process "/bin/sh -c dotnet publish -c Release -o /app/publish" did not complete successfully: exit code: 1

View build details: docker-desktop://dashboard/build/desktop-linux/desktop-linux/id1ktua3pu6cs6phrk96gftni

   Resourcely   git:(JaniduLoginSignupCoud) 

 <PackageReference Include="MySqlConnector" Version="2.4.0" />  package is outdadted

missing npm [pack:
   * @radix-ui/react-slot
   * @radix-ui/react-dialog
   * @radix-ui/react-select
   * class-variance-authority
   * clsx
   * tailwind-merge